In [5]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("customer.csv")

In [3]:
df.sample(10)

    age  gender   review education purchased
10   98  Female     Good        UG       Yes
47   38  Female     Good        PG       Yes
34   86    Male  Average    School        No
32   92    Male  Average        UG       Yes
30   73    Male  Average        UG        No
18   19    Male     Good    School        No
1    68  Female     Poor        UG        No
3    72  Female     Good        PG        No
26   53  Female     Poor        PG        No
40   39    Male     Good    School        No

In [4]:
df = df.iloc[:, 2:]

In [6]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [7]:
xtrain, xtest, ytrain, ytest =  train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.25)

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df['education'].unique()
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [15]:
oe = OrdinalEncoder(categories=[['Poor','Average', 'Good'], ['School', 'UG', 'PG']])

In [19]:
oe.fit(xtrain)
oe.transform(xtrain)
oe.transform(xtest)

array([[2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [0., 2.]])

In [20]:
xtest.head()

     review education
11     Good        UG
41     Good        PG
29  Average        UG
24  Average        PG
20  Average    School

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [26]:
le.fit(ytrain)
ytrain = le.transform(ytrain)
ytest = le.transform(ytest)
le.classes_
ytest

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0])